spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ffuhome?useUnicode=true&characterEncoding=utf-8&useSSL=true&zeroDateTimeBehavior=CONVERT_TO_NULL&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
  thymeleaf:
    cache: false

server:
  port: 8080

sms:
  enabled: false

my:
  userfiles-basedir: D:/workspace/test/nas/ffu/home/